version: '3.5'
services:
  api-service:
    environment:
      SERVICE_NAME: app
    working_dir: /var/www
    entrypoint: /etc/entrypoint.sh
    volumes:
      - ../../:/var/www
      - ../../composer-auth.json:/root/.composer/auth.json
      - ../nginx/conf.d/nginx-dev.conf:/etc/nginx/sites-enabled/default
      - ../php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ../php/memory_limit.ini:/usr/local/etc/php/conf.d/memory_limit.ini
    ports:
      - ${PORT}:80

networks:
  api-service-network:
    driver: bridge
