version: '3.5'
services:
  api-service:
    environment:
      SERVICE_NAME: app
    volumes:
      - ../nginx/conf.d/nginx-dev.conf:/etc/nginx/sites-enabled/default
      - ~/.composer/auth.json:/root/.composer/auth.json
    ports:
      - ${PORT}:80

networks:
  api-service-network:
    driver: bridge
