version: '3.5'
services:
  api-service:
    image: registry.sheba.xyz/${CONTAINER_NAME}
    environment:
      SERVICE_NAME: app
      VIRTUAL_HOST: ${API_DOMAIN}
    ports:
      - ${PORT}:80

networks:
  api-service-network:
    external:
      name: ${EXTERNAL_NETWORK}
