version: '3.5'
services:
  api-service:
    container_name: api-service
    restart: unless-stopped
    tty: true
    env_file: ../../.env
    working_dir: /var/www
    volumes:
      - ../../:/var/www
      - ../php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ../php/memory_limit.ini:/usr/local/etc/php/conf.d/memory_limit.ini
    networks:
      - api-service-network
