version: '3.5'
services:
  api-service:
    environment:
      SERVICE_NAME: app
      VIRTUAL_HOST: ${API_DOMAIN}
    volumes:
      - ../nginx/conf.d/nginx-local.conf:/etc/nginx/sites-enabled/default
    ports: 
      - ${PORT}:80

networks:
  api-service-network:    
    external:
      name: sheba-docker_development_network
