version: '3.5'
services:
  api-service:
    environment:
      SERVICE_NAME: app
    volumes:
      - ../nginx/conf.d/nginx-prod.conf:/etc/nginx/sites-enabled/default
    ports: 
      - "80:80"

networks:
  api-service-network:
    driver: bridge
