version: '3.5'
services:
  api-service:
    environment:
      SERVICE_NAME: app
      VIRTUAL_HOST: ${API_DOMAIN}
    volumes:
      - ../nginx/conf.d/nginx-local.conf:/etc/nginx/sites-enabled/default
    ports:
      - ${PORT}:80
    extra_hosts:
      - "${VIRTUAL_HOST_DOCKER_HOST}:${DOCKER_HOST_ADDR}"
      - "${VIRTUAL_HOST_LOCALHOST}:${DOCKER_HOST_ADDR}"
      - "${VIRTUAL_HOST_ADMIN}:${DOCKER_HOST_ADDR}"
      - "${VIRTUAL_HOST_API}:${DOCKER_HOST_ADDR}"
      - "${VIRTUAL_HOST_ACCOUNTS}:${DOCKER_HOST_ADDR}"
      - "${VIRTUAL_HOST_WALLET}:${DOCKER_HOST_ADDR}"
      - "${VIRTUAL_HOST_API_LOGISTICS}:${DOCKER_HOST_ADDR}"
      - "${VIRTUAL_HOST_REPORTS}:${DOCKER_HOST_ADDR}"
      - "${VIRTUAL_HOST_EXPENSE}:${DOCKER_HOST_ADDR}"

networks:
  api-service-network:
    external:
      name: ${EXTERNAL_NETWORK}
