<?php namespace Sheba\Business\AttendanceActionLog\ActionChecker;

use Carbon\Carbon;
use Sheba\Business\AttendanceActionLog\StatusCalculator\ShiftCheckinStatusCalculator;
use Sheba\Business\Leave\HalfDay\HalfDayLeaveCheck;
use Sheba\Dal\AttendanceActionLog\Actions;
use Sheba\Business\AttendanceActionLog\TimeByBusiness;
use Sheba\Business\AttendanceActionLog\WeekendHolidayByBusiness;
use Sheba\Dal\Attendance\Statuses;

class CheckIn extends ActionChecker
{
    public function getActionName()
    {
        return Actions::CHECKIN;
    }

    public function check()
    {
        parent::check(); // TODO: Change the autogenerated stub
        $this->checkForLateAction();
    }

    protected function setAlreadyHasActionForTodayResponse()
    {
        $this->setResult(ActionResult::ALREADY_CHECKED_IN);
    }

    protected function checkForLateAction()
    {
        if ($this->isAlreadyFailed()) return;

        if ($this->isNotInShift()) {
            $this->checkForGeneral();
        } else {
            $this->checkForShift();
        }
    }

    protected function checkForGeneral()
    {
        $date = Carbon::now();
        $weekendHoliday = new WeekendHolidayByBusiness();

        $which_half_day = $this->getHalfDay();
        $today_last_checkin_time = $this->business->calculationTodayLastCheckInTime($which_half_day);

        if (is_null($today_last_checkin_time)) return;

        $today_checkin_time_without_second = Carbon::parse($date->format('Y-m-d H:i'));
        $is_full_day_leave = (new HalfDayLeaveCheck())->setBusinessMember($this->businessMember)->checkFullDayLeave();

        if ($today_checkin_time_without_second->greaterThan($today_last_checkin_time)) {
            if ($weekendHoliday->isWeekendByBusiness($date) || $weekendHoliday->isHolidayByBusiness($date) || $is_full_day_leave) {
                $this->setResult(ActionResult::SUCCESSFUL);
            } else {
                $this->setResult(ActionResult::LATE_TODAY);
            }
        }
    }

    protected function checkForShift()
    {
        /** @var ShiftCheckinStatusCalculator $shiftCheckinStatusCalculator */
        $shiftCheckinStatusCalculator = app(ShiftCheckinStatusCalculator::class);

        $which_half_day = $this->getHalfDay();

        $status = $shiftCheckinStatusCalculator
            ->setBusinessMember($this->businessMember)
            ->setShiftAssignment($this->shiftAssignment)
            ->setWhichHalfDay($which_half_day)
            ->calculate();

        if ($status == Statuses::ON_TIME) {
            $this->setResult(ActionResult::SUCCESSFUL);
        } else if ($status == Statuses::LATE) {
            $this->setResult(ActionResult::LATE_TODAY);
        }
    }
}
